### PR TITLE
Micronaut Core 4.3 SNAPSHOT

### PR DESCRIPTION
**Pull request by dstepanov**

### CODE REVIEW

**Comment by yawkat** [comment]
@dstepanov i think we should just revert the parameter change in https://github.com/micronaut-projects/micronaut-core/pull/10167 , it's not necessary for the performance improvements and it's much easier to revert than to fix breakage here

**Review by wetted — COMMENTED** [review]
I don't think we should be pointing to snapshots to fix this. It blocks us from doing any releases from master until core is released.

**Comment by wetted** [comment]
> @wetted What kind of releases are you planning to do?

I'm speaking generally. I'm not planning any releases. Happy to be corrected if I'm wrong, but it seems unusual for us to point modules to snapshots if we aren't developing towards another major release of the framework.

**Comment by wetted** [comment]
> Well, it did break the starter which is using snapshots, I think I will fix the core to be compatible like Jonas suggested.

Fair enough. I'd like to understand any guidelines we intend for using or not using snapshots in modules for development.

**Pull request closed without merging**
