### PR TITLE
Servlet StreamTest fails after upgrading to M7

### PR DESCRIPTION
**Pull request by sdelamo**

### CODE REVIEW

**Comment by timyates** [comment]
StreamTest is new in M7

I suspect this has never worked in Servlet, even in Micronaut 3.x...  I will verify, and if so I'll work on a fix in 3.3.x

**Comment by timyates** [comment]
I'll work on this PR https://github.com/micronaut-projects/micronaut-servlet/pull/482 to try and get a fix

**Comment by sdelamo** [comment]
@timyates  can you merge up from 3.4.x into this branch and see if StreamTest passes?

**Comment by timyates** [comment]
Superseded by https://github.com/micronaut-projects/micronaut-servlet/pull/486

**Pull request closed without merging**
