### PR TITLE
Migration to Micronaut 4

### PR DESCRIPTION
**Pull request by dstepanov**
PR uses refactored routing API from Core eliminating duplicate code.

There are some unresolved errors caused by CORS not doing the same as before and errors caused by serde migrations.

### CODE REVIEW

**Comment by dstepanov** [comment]
@sdelamo Can you please investigate the CORS errors?

**Comment by sdelamo** [comment]
> @sdelamo Can you please investigate the CORS errors?

@timyates could you do that?

**Comment by timyates** [comment]
Ok, so I've take a look at the CORS failures...

What I suspect is happening is that HttpClient has changed to keep-alive as default

https://github.com/micronaut-projects/micronaut-core/pull/8100#discussion_r984590458

And Jetty doesn't return `Connection: keep-alive` headers, as that is the default for HTTP 1.1

I'll go with this, and get a commit together that goes with this expectation

**Comment by timyates** [comment]
@dstepanov Fixed the cors errors...

There are still binding errors, and fields not being bound from Json

Can you take a look?

**Review by graemerocher — APPROVED** [review]

**Pull request merged**
