### PR TITLE
Remove dependency on Netty

### PR DESCRIPTION
**Pull request by driverpt**

### CODE REVIEW

**Comment by driverpt** [comment]
@graemerocher @sdelamo , Build is failing with this error:
```
org.sonar.api.utils.MessageException: Project not found. Please check the 'sonar.projectKey' and 'sonar.organization' properties, the 'SONAR_TOKEN' environment variable, or contact the project administrator
```

**Comment by sdelamo** [comment]
@driverpt can you please target 3.4.x as the base of this PR?. Thanks

**Comment by driverpt** [comment]
Rebased!

**Comment by driverpt** [comment]
@sdelamo @graemerocher , can we create our own cookie parser in  `ServletCookies`?

**Comment by driverpt** [comment]
What about migrating to `java.net.HttpCookie` ?

**Comment by driverpt** [comment]
Nevermind, `java.net.HttpCookie` doesn't have `SameSite`

**Comment by sdelamo** [comment]
Closing this PR since we would need more changes to remove `micronaut.http.netty` dependency.

It does not compile.
```
/home/runner/work/micronaut-servlet/micronaut-servlet/servlet-core/src/main/java/io/micronaut/servlet/http/ServletCookies.java:23: error: package io.micronaut.http.netty.cookies does not exist
[75](https://github.com/micronaut-projects/micronaut-servlet/actions/runs/4425655997/jobs/7788599236?pr=411#step:8:76)

[76](https://github.com/micronaut-projects/micronaut-servlet/actions/runs/4425655997/jobs/7788599236?pr=411#step:8:77)
import io.micronaut.http.netty.cookies.NettyCookie;
[77](https://github.com/micronaut-projects/micronaut-servlet/actions/runs/4425655997/jobs/7788599236?pr=411#step:8:78)
                                      ^
[78](https://github.com/micronaut-projects/micronaut-servlet/actions/runs/4425655997/jobs/7788599236?pr=411#step:8:79)
/home/runner/work/micronaut-servlet/micronaut-servlet/servlet-core/src/main/java/io/micronaut/servlet/http/ServletCookies.java:24: error: package io.netty.handler.codec.http.cookie does not exist
[79](https://github.com/micronaut-projects/micronaut-servlet/actions/runs/4425655997/jobs/7788599236?pr=411#step:8:80)
import io.netty.handler.codec.http.cookie.ServerCookieDecoder;
[80](https://github.com/micronaut-projects/micronaut-servlet/actions/runs/4425655997/jobs/7788599236?pr=411#step:8:81)
                                         ^
[81](https://github.com/micronaut-projects/micronaut-servlet/actions/runs/4425655997/jobs/7788599236?pr=411#step:8:82)
/home/runner/work/micronaut-servlet/micronaut-servlet/servlet-core/src/main/java/io/micronaut/servlet/http/ServletHttpHandler.java:68: error: package io.netty.handler.codec.http does not exist
[82](https://github.com/micronaut-projects/micronaut-servlet/actions/runs/4425655997/jobs/7788599236?pr=411#step:8:83)
import io.netty.handler.codec.http.HttpHeaderValues;
[83](https://github.com/micronaut-projects/micronaut-servlet/actions/runs/4425655997/jobs/7788599236?pr=411#step:8:84)
                                  ^
```

**Pull request closed without merging**
