### PR TITLE
Add binary-configuration to servlet-core

### PR DESCRIPTION
**Pull request by timyates**
This class was used in both AWS and Azure, so we have pulled it up into servlet-core

### CODE REVIEW

**Review by sdelamo — CHANGES_REQUESTED** [review]
It misses a test

**Review by sdelamo — APPROVED** [review]
I added a unit test

**Comment by sdelamo** [comment]
I think more about this I think we should do this in core and it should be probably configurable. For example:  A user may want to set: 

`micronaut.http.binary-types.additional-types`

to add extra types to the list we provide by default.

**Comment by timyates** [comment]
Superseded by https://github.com/micronaut-projects/micronaut-core/pull/9530

**Pull request closed without merging**
